---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-0.30
  commands:
  - docker build --pull -t nephatrine/nginx-h5ai:0.30 .
  - HOME=/mnt/config/home docker push nephatrine/nginx-h5ai:0.30
- name: build-latest
  commands:
  - docker tag nephatrine/nginx-h5ai:0.30 pdr.nephatrine.net/nephatrine/nginx-h5ai:latest
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/nginx-h5ai:latest
  - docker tag pdr.nephatrine.net/nephatrine/nginx-h5ai:latest nephatrine/nginx-h5ai:latest
  - HOME=/mnt/config/home docker push nephatrine/nginx-h5ai:latest
  - docker rmi pdr.nephatrine.net/nephatrine/nginx-h5ai:latest
  depends_on:
  - build-0.30

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: 431af154f92e3b2531db94ecbf84441da20cc8413ce7bbef1af8d0bc0f99485e

...
